# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('x_loc', models.IntegerField()),
                ('y_loc', models.IntegerField()),
                ('dest_addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('x_loc', models.IntegerField()),
                ('y_loc', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Truck'),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Package'),
        ),
    ]
