# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='x_loc',
            new_name='dest_addr_x',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='y_loc',
            new_name='dest_addr_y',
        ),
        migrations.RemoveField(
            model_name='package',
            name='dest_addr',
        ),
    ]
