# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_auto_20170426_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('dest_addr_x', models.IntegerField()),
                ('dest_addr_y', models.IntegerField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Truck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='package',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AddField(
            model_name='item',
            name='shipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.Shipment'),
        ),
    ]
