# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20170427_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
